apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: team-emottak
  name: smtp.out.ebxml.signal
  namespace: team-emottak
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: delete
    maxMessageBytes: 1048588
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 168
    segmentHours: 168
  acl:
    - access: write
      application: ebms-provider
      team: team-emottak
    - access: read
      application: emottak-kafka-manager
      team: team-emottak
