apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: team-emottak
  name: smtp.out.ebxml.signal
  namespace: team-emottak
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    maxMessageBytes: 1048588
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 4380
    segmentHours: 168
  acl:
    - access: write
      application: ebms-async
      team: team-emottak
    - access: read
      application: smtp-transport
      team: team-emottak
    - access: read
      application: emottak-kafka-manager
      team: team-emottak

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: team-emottak
  name: smtp.out.ebxml.payload
  namespace: team-emottak
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    maxMessageBytes: 1048588
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 4380
    segmentHours: 168
  acl:
    - access: write
      application: ebms-async
      team: team-emottak
    - access: read
      application: smtp-transport
      team: team-emottak
    - access: read
      application: emottak-kafka-manager
      team: team-emottak

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: team-emottak
  name: ebxml.retry
  namespace: team-emottak
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    maxMessageBytes: 1048588
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 4380
    segmentHours: 168
  acl:
    - access: readwrite
      application: ebms-async
      team: team-emottak
    - access: read
      application: emottak-kafka-manager
      team: team-emottak

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ebms.in.payload
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  pool: nav-prod
  acl:
    - team: team-emottak
      application: ebms-async
      access: write   # read, write, readwrite

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ebms.out.payload
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  pool: nav-prod
  acl:
    - team: team-emottak
      application: ebms-async
      access: read   # read, write, readwrite
