/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
}

tasks.register<Wrapper>("wrapper") {
    gradleVersion="8.1.1"
}

dependencies {
    implementation(libs.ebxml.protokoll)
    implementation(libs.hikari)
    implementation(libs.flyway.core)
    implementation(libs.logback.classic)
    implementation(libs.ktor.serialization.kotlinx.json)
    api(libs.bcprov.jdk18on)
    api(libs.bcpkix.jdk18on)
    testImplementation(testLibs.junit.jupiter.api)
    testRuntimeOnly(testLibs.junit.jupiter.engine)

    runtimeOnly("org.postgresql:postgresql:42.6.0")
}

