apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-payload"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 1
    max: 5
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-payload-fss.intern.nav.no"
  accessPolicy:
    outbound:
      rules:
        - application: cpa-repo
    inbound:
      rules:
        - application: ebms-provider
  vault:
    enabled: true
  webproxy: true
  env:
    - name: VIRKSOMHETSSERTIFIKAT_PATH
      value: /secret/virksomhetssertifikat/prod/Arbeids-og-velferdsetaten
    - name: VIRKSOMHETSSERTIFIKAT_SIGNERING
      value: key.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_DEKRYPTERING
      value: key.decrypt.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_CREDENTIALS
      value: credentials.2022
