apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-provider"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-provider.intern.dev.nav.no"
  gcp:
    sqlInstances:
        - type: POSTGRES_15
          databases:
            - name: ebms-db
  accessPolicy:
    outbound:
      rules:
        - application: cpa-repo
        - application: ebms-payload
