apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "smtp-router"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://smtp-router.intern.dev.nav.no"
  env:
    - name: SMTP_POP3_FACTORY_PORT
      value: "3110"
    - name: SMTP_POP3_PORT
      value: "3110"
    - name: SMTP_POP3_HOST
      value: "localhost"
    - name: SMTP_STORE_PROTOCOL
      value: "pop3"
    - name: SMTP_USERNAME
      value: "test@test.test"
