apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "async-recievers"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  liveness:
    path: "/internal/health/ping"
    port: 8080
    initialDelay: 60
    timeout: 30
    failureThreshold: 20
  readiness:
    path: "/internal/health"
    port: 8080
    initialDelay: 60
    timeout: 30
    failureThreshold: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
    - type: "POSTGRES_15"
      databases:
        - "name": "ebxml-processor-db"
      flags:
        - name: max_connections
          value: "50"
  kafka:
    pool: {{kafka.pool}}