apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "cpa-repo"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 25
    min: 1
    max: 4
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://cpa-repo-fss.intern.dev.nav.no"
    - "https://cpa-repo.dev-fss-pub.nais.io"
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/emottak_q1-nmt3
        mountPath: /secrets/oracle/creds
      - kvPath: /oracle/data/dev/config/emottak_q1
        mountPath: /secrets/oracle/config
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: smtp-listeners
        - application: ebms-provider
        - application: ebms-payload
    outbound:
      external:
        - host: crl.buypass.no
          ports:
            - port: 80
        - host: crl.test4.buypass.no
          ports:
            - port: 80
        - host: crl.buypassca.com
          ports:
            - port: 80
        - host: crl.test4.buypassca.com
          ports:
            - port: 80
        - host: crl.commfides.com
        - host: crl.test.commfides.com
        - host: crl1.commfides.com
          ports:
            - port: 80
        - host: crl1.test.commfides.com
          ports:
            - port: 80
  env:
    - name: VAULT_JDBC_URL
      value: jdbc:postgresql://b27dbvl033.preprod.local:5432/
    - name: TRUSTSTORE_PATH
      value: truststore_test.p12
