apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "cpa-repo"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 25
    min: 1
    max: 4
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://cpa-repo-fss.intern.dev.nav.no"
    - "https://cpa-repo.dev-fss-pub.nais.io"
  filesFrom:
    - secret: emottak-ar-klient-secret
      mountPath: /var/run/secrets/emottak-ar-klient-secret
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/emottak_q1-nmt3
        mountPath: /secrets/oracle/creds
      - kvPath: /oracle/data/dev/config/emottak_q1
        mountPath: /secrets/oracle/config
  kafka:
    pool: nav-dev
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: cpa-sync
        - application: ebms-async
        - application: ebms-provider
        - application: ebms-payload
        - application: emottak-monitor
    outbound:
      external:
        - host: crl.buypass.no
          ports:
            - port: 80
        - host: crl.test4.buypass.no
          ports:
            - port: 80
        - host: crl.buypassca.com
          ports:
            - port: 80
        - host: crl.test4.buypassca.com
          ports:
            - port: 80
        - host: crl.commfides.com
        - host: crl.test.commfides.com
        - host: crl1.commfides.com
          ports:
            - port: 80
        - host: crl1.test.commfides.com
          ports:
            - port: 80
  env:
    - name: VAULT_JDBC_URL
      value: jdbc:postgresql://b27dbvl033.preprod.local:5432/
    - name: TRUSTSTORE_PATH
      value: truststore_test.p12
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG
    - name: MAX_CONNECTION_POOL_SIZE_FOR_USER
      value: "4"
    - name: MAX_CONNECTION_POOL_SIZE_FOR_ADMIN
      value: "1"
    - name: ORACLE_CREDENTIAL_SECRET_PATH
      value: /secrets/oracle/creds
    - name: ORACLE_CONFIG_SECRET_PATH
      value: /secrets/oracle/config
    - name: ADRESSE_REGISTER_URL
      value: https://cpapi.test.grunndata.nhn.no/CommunicationParty/
    - name: NHN_KEYPAIR_PATH
      value: "/var/run/secrets/emottak-ar-klient-secret/key"
    - name: NHN_TOKEN_ENDPOINT
      value: "https://helseid-sts.test.nhn.no/connect/token"
    - name: NHN_CLIENT_KEY_ID
      value: "xMd3Jezu0PaRNBIxUZK8j8wBh7N7Bc6c-9MOt5AchbU"
    - name: NHN_CLIENT_ID
      value: "ab926758-4a6f-41fa-9c69-9ae1dd095662"
    - name: NHN_CLIENT_AUDIENCE
      value: "https://helseid-sts.test.nhn.no"
    - name: NHN_CLIENT_SCOPE
      value: "nhn:msh/api"
    - name: NHN_CLIENT_GRANT_TYPE
      value: "client_credentials"
    - name: NHN_CLIENT_ASSERTION_TYPE
      value: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
