apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "cpa-repo"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://cpa-repo-fss.intern.dev.nav.no"
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/emottak_q1-nmt3
        mountPath: /secrets/oracle/creds
      - kvPath: /oracle/data/dev/config/emottak_q1
        mountPath: /secrets/oracle/config
  webproxy: true
#  gcp:
#    sqlInstances:
#        - type: POSTGRES_15
#          databases:
#            - name: cpa-repo-db
  accessPolicy:
    inbound:
      rules:
        - application: smtp-listeners
        - application: ebms-provider
        - application: ebms-payload
    outbound:
      external:
        - host: crl.buypassca.com
          ports:
            - port: 80
        - host: crl.test4.buypass.no
          ports:
            - port: 80
        - host: crl.test4.buypassca.com
          ports:
            - port: 80
