apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "cpa-repo"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  ingresses:
    - "https://cpa-repo-fss.intern.nav.no"
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/emottak-nmp5
        mountPath: /secrets/oracle/creds
      - kvPath: /oracle/data/prod/config/emottak
        mountPath: /secrets/oracle/config
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: smtp-listeners
        - application: ebms-provider
        - application: ebms-payload
    outbound:
      external:
        - host: crl.buypassca.com
          ports:
            - port: 80
        - host: crl.buypass.no
          ports:
            - port: 80
        - host: crl.buypassca.com
          ports:
            - port: 80
