apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "cpa-repo"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 35
    min: 2
    max: 4
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  ingresses:
    - "https://cpa-repo-fss.intern.nav.no"
    #- "https://cpa-repo.prod-fss-pub.nais.io"
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/emottak-nmp5
        mountPath: /secrets/oracle/creds
      - kvPath: /oracle/data/prod/config/emottak
        mountPath: /secrets/oracle/config
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: smtp-listeners
        - application: ebms-provider
        - application: ebms-payload
    outbound:
      external:
        - host: crl.buypassca.com
          ports:
            - port: 80
        - host: crl.buypass.no
          ports:
            - port: 80
        - host: crl.commfides.com
        - host: crl1.commfides.com
          ports:
            - port: 80
  env:
    - name: VAULT_JDBC_URL
      value: jdbc:postgresql://A01DBVL037.adeo.no:5432/
    - name: TRUSTSTORE_PATH
      value: truststore_prod.p12
