apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-send-in"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-send-in.intern.dev.nav.no"
  vault:
    enabled: true
    paths:
        - kvPath: /serviceuser/data/dev/srvtokt
          mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: ebms-provider