apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-send-in"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - https://ebms-send-in.intern.nav.no
  vault:
    enabled: true
    paths:
        - kvPath: /serviceuser/data/dev/srvtokt
          mountPath: /secret/serviceuser

