apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-provider"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 25
    min: 4
    max: 12
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "512Mi"
  ingresses:
    - "https://ebms-provider-fss.intern.nav.no"
  vault:
    enabled: true
  kafka:
    pool: nav-prod
  accessPolicy:
    inbound:
      rules:
        - application: statuspoll
          namespace: navdig
    outbound:
      rules:
        - application: cpa-repo
        - application: ebms-payload
        - application: ebms-send-in
  env:
    - name: VIRKSOMHETSSERTIFIKAT_PATH
      value: /secret/virksomhetssertifikat/prod/Arbeids-og-velferdsetaten
    - name: VIRKSOMHETSSERTIFIKAT_SIGNERING_2022
      value: key.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_DEKRYPTERING_2022
      value: key.decrypt.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_CREDENTIALS_2022
      value: credentials.2022
    - name: VIRKSOMHETSSERTIFIKAT_SIGNERING_2025
      value: key.p12.b64.2025
    - name: VIRKSOMHETSSERTIFIKAT_DEKRYPTERING_2025
      value: key.decrypt.p12.b64.2025
    - name: VIRKSOMHETSSERTIFIKAT_CREDENTIALS_2025
      value: credentials.2025
    - name: CPA_REPO_URL
      value: http://cpa-repo.team-emottak.svc.nais.local
    - name: PAYLOAD_PROCESSOR_URL
      value: http://ebms-payload
    - name: SEND_IN_URL
      value: http://ebms-send-in
    - name: SMTP_TRANSPORT_URL
      value: http://smtp-transport
    - name: EVENT_MANAGER_URL
      value: http://emottak-event-manager
