apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-payload"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 2
    max: 5
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "768Mi"
  ingresses:
    - "https://ebms-payload-fss.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: ebms-provider
        - application: ebms-async
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srv-ebms-payload
        mountPath: /var/run/secrets/nais.io/vault/serviceuser
  kafka:
    pool: nav-prod
  webproxy: true
  env:
    - name: VIRKSOMHETSSERTIFIKAT_PATH
      value: /secret/virksomhetssertifikat/prod/Arbeids-og-velferdsetaten
    - name: VIRKSOMHETSSERTIFIKAT_SIGNERING_2022
      value: key.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_DEKRYPTERING_2022
      value: key.decrypt.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_CREDENTIALS_2022
      value: credentials.2022
    - name: VIRKSOMHETSSERTIFIKAT_SIGNERING_2025
      value: key.p12.b64.2025
    - name: VIRKSOMHETSSERTIFIKAT_DEKRYPTERING_2025
      value: key.decrypt.p12.b64.2025
    - name: VIRKSOMHETSSERTIFIKAT_CREDENTIALS_2025
      value: credentials.2025
    - name: TRUSTSTORE_PATH
      value: truststore_prod.p12
    - name: APP_JURIDISKLOGG_URI
      value: https://app.adeo.no/juridisklogg
    - name: JURIDISKLOGG_STORAGE_TIME_YEARS
      value: "10"
    - name: JURIDISKLOGG_SERVICEUSER_SECRET_PATH
      value: /var/run/secrets/nais.io/vault/serviceuser
    - name: JDK_JAVA_OPTIONS
      value: "$(JAVA_PROXY_OPTIONS)"