apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-payload"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 1
    max: 5
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-payload-fss.intern.nav.no"
  accessPolicy:
    outbound:
      rules:
        - application: cpa-repo
    inbound:
      rules:
        - application: ebms-provider
  vault:
    enabled: true
    paths:
      - kvPath: /secret/virksomhetssertifikat/prod/Arbeids-og-velferdsetaten
        mountPath: /var/run/secrets/ebms-keystore
  env:
    - name: KEYSTORE_FILE_DEKRYPT
      value: /var/run/secrets/ebms-keystore/key.decrypt.p12.b64.2022
    - name: KEYSTORE_FILE_SIGN
      value: /var/run/secrets/ebms-keystore/key.p12.b64.2022
    - name: KEYSTORE_PWD_FILE
      value: /var/run/secrets/ebms-keystore/credentials.2022
#  envFrom:
#    - secret: ebms-payload-secret
#  filesFrom:
#    - secret: ebms-payload-keystore
#      mountPath: /var/run/secrets/ebms-keystore
