apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-async"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 30
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "100m"
      memory: "512Mi"
  ingresses:
    - "https://ebms-async-fss.intern.nav.no"
  vault:
    enabled: true
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      rules:
        - application: cpa-repo
        - application: ebms-payload
        - application: ebms-send-in
        - application: smtp-transport
    inbound:
      rules:
        - application: smtp-transport
  env:
    - name: VIRKSOMHETSSERTIFIKAT_PATH
      value: /secret/virksomhetssertifikat/prod/Arbeids-og-velferdsetaten
    - name: VIRKSOMHETSSERTIFIKAT_SIGNERING
      value: key.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_DEKRYPTERING
      value: key.decrypt.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_CREDENTIALS
      value: credentials.2022
    - name: MAX_CONNECTION_POOL_SIZE_FOR_USER
      value: "4"
    - name: MAX_CONNECTION_POOL_SIZE_FOR_ADMIN
      value: "1"
    - name: EBMS_SIGNAL_RECEIVER
      value: "true"
    - name: EBMS_SIGNAL_PRODUCER
      value: "true"
    - name: EBMS_PAYLOAD_RECEIVER
      value: "true"
    - name: EBMS_PAYLOAD_PRODUCER
      value: "true"
    - name: EBMS_RETRY_QUEUE
      value: "true"
    - name: VAULT_JDBC_URL
      value: jdbc:postgresql://A01DBVL037.adeo.no:5432/
    - name: CPA_REPO_URL
      value: http://cpa-repo.team-emottak.svc.nais.local
    - name: PAYLOAD_PROCESSOR_URL
      value: http://ebms-payload
    - name: SEND_IN_URL
      value: http://ebms-send-in
    - name: SMTP_TRANSPORT_URL
      value: http://smtp-transport
