apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-provider"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 30
    min: 1
    max: 6
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-provider-fss.intern.dev.nav.no"
  vault:
    enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: cpa-repo
        - application: ebms-payload
        - application: ebms-send-in
  env:
    - name: KEYSTORE_FILE_SIGN_2022
      value: /var/run/secrets/ebms-keystore-signering/signering-key.p12
    - name: KEYSTORE_FILE_SIGN_2025
      value: /var/run/secrets/ebms-keystore-signering-2025/signering-key.p12
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG
    - name: CPA_REPO_URL
      value: http://cpa-repo.team-emottak.svc.nais.local
    - name: PAYLOAD_PROCESSOR_URL
      value: http://ebms-payload
    - name: SEND_IN_URL
      value: http://ebms-send-in
    - name: SMTP_TRANSPORT_URL
      value: http://smtp-transport
  envFrom:
    - secret: ebms-payload-secret
    - secret: ebms-keystore-pwd-2025
  filesFrom:
    - secret: ebms-keystore-signering
      mountPath: /var/run/secrets/ebms-keystore-signering
    - secret: ebms-keystore-sign-2025
      mountPath: /var/run/secrets/ebms-keystore-signering-2025
