apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-send-in"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 25
    min: 2
    max: 12
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  ingresses:
    - https://ebms-send-in.intern.nav.no
  vault:
    enabled: true
    paths:
        - kvPath: /serviceuser/data/prod/srvtokt
          mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: ebms-provider
  env:
    - name: FRIKORT_URL
      value: https://wasapp.adeo.no/nav-frikort/tjenestereksterne