apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-provider"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 25
    min: 2
    max: 12
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "512Mi"
  ingresses:
    - "https://ebms-provider-fss.intern.nav.no"
  vault:
    enabled: true
  kafka:
    pool: nav-prod
#  gcp:
#    sqlInstances:
#        - type: POSTGRES_15
#          databases:
#            - name: ebms-db
  accessPolicy:
    inbound:
      rules:
        - application: statuspoll
          namespace: navdig
        - application: smtp-transport
    outbound:
      rules:
        - application: cpa-repo
        - application: ebms-payload
  env:
    - name: VIRKSOMHETSSERTIFIKAT_PATH
      value: /secret/virksomhetssertifikat/prod/Arbeids-og-velferdsetaten
    - name: VIRKSOMHETSSERTIFIKAT_SIGNERING
      value: key.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_DEKRYPTERING
      value: key.decrypt.p12.b64.2022
    - name: VIRKSOMHETSSERTIFIKAT_CREDENTIALS
      value: credentials.2022
    - name: MAX_CONNECTION_POOL_SIZE_FOR_USER
      value: "4"
    - name: MAX_CONNECTION_POOL_SIZE_FOR_ADMIN
      value: "2"
    - name: SIGNAL_RECEIVER
      value: "false"
    - name: SIGNAL_PRODUCER
      value: "false"
    - name: VAULT_JDBC_URL
      value: jdbc:postgresql://A01DBVL037.adeo.no:5432/
