apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-payload"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-payload-fss.intern.dev.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: ebms-provider
        - application: ebms-async
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srv-ebms-payload
        mountPath: /var/run/secrets/nais.io/vault/serviceuser
  kafka:
    pool: nav-dev
  webproxy: true
  envFrom:
    - secret: ebms-payload-secret
  filesFrom:
    - secret: ebms-payload-sign-keystore
      mountPath: /var/run/secrets/ebms-signing-keystore
    - secret: ebms-payload-enc-keystore
      mountPath: /var/run/secrets/ebms-encryption-keystore
  env:
    - name: KEYSTORE_FILE_DEKRYPT
      value: /var/run/secrets/ebms-encryption-keystore/nav_encryption_test.p12
    - name: KEYSTORE_FILE_SIGN
      value: /var/run/secrets/ebms-signing-keystore/nav_signing_test.p12
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG
    - name: TRUSTSTORE_PATH
      value: truststore_test.p12
    - name: APP_JURIDISKLOGG_URI
      value: https://app-q1.adeo.no/juridisklogg
    - name: JURIDISKLOGG_STORAGE_TIME_YEARS
      value: "1"
    - name: JURIDISKLOGG_SERVICEUSER_SECRET_PATH
      value: /var/run/secrets/nais.io/vault/serviceuser
    - name: JDK_JAVA_OPTIONS
      value: "$(JAVA_PROXY_OPTIONS)"
