apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-payload"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-payload.intern.dev.nav.no"
  accessPolicy:
    outbound:
      rules:
        - application: cpa-repo
    inbound:
      rules:
        - application: ebms-provider
