apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: team-emottak
  name: mailreader
  namespace: team-emottak
spec:
  ttlSecondsAfterFinished: 180
  image: {{image}}
  schedule: "*/5 * * * *"
  command:
    - curl
    - http://smtp-listeners/mail/read