apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "emottak-payload-processor"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://emottak-payload-processor.intern.dev.nav.no"