/*
 * This file was generated by the Gradle 'init' task.
 */
import java.time.LocalDate
import java.time.format.DateTimeFormatter

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
    id("maven-publish")
    id("java-library")
}

tasks {
    register<Wrapper>("wrapper") {
        gradleVersion="8.1.1"
    }
    test {
        useJUnitPlatform()
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            groupId = "no.nav.emottak"
            artifactId = "ebxml-processing-model"
            version = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyyMMdd")) + System.getenv("GITHUB_SHA")
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/navikt/ebxml-processor")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

dependencies {
    implementation(libs.ebxml.protokoll)
    implementation(libs.emottak.payload.xsd)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.bundles.logging)
    runtimeOnly("org.postgresql:postgresql:42.6.0")
}

