/*
 * This file was generated by the Gradle 'init' task.
 */
import java.time.LocalDate
import java.time.format.DateTimeFormatter

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
    id("maven-publish")
    id("java-library")
    id("org.jlleitschuh.gradle.ktlint") version "11.6.1"
}

kotlin {
    jvmToolchain(21)
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            groupId = "no.nav.emottak"
            artifactId = "ebxml-processing-model"
            version = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyyMMdd")) + System.getenv("GITHUB_SHA")
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/navikt/${rootProject.name}")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

dependencies {
    implementation(libs.ebxml.protokoll)
    implementation(libs.emottak.payload.xsd)
    implementation(libs.emottak.utils)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.jaxb.runtime)
    implementation(libs.bundles.logging)
    runtimeOnly("org.postgresql:postgresql:42.7.3")
}

tasks {
    test {
        useJUnitPlatform()
    }
    ktlintFormat {
        this.enabled = true
    }
    ktlintCheck {
        dependsOn("ktlintFormat")
    }
    build {
        dependsOn("ktlintCheck")
    }
}
