spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security:
        protocol: PLAINTEXT
      ssl:
        key.password: changeit
        truststore:
          location:
          password: changeit
        keystore:
          location:
          password: changeit
      schema.registry.url: mock://localhost
      basic:
        auth:
          user:
            info: user:password