/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.emottak.ebms.async

import arrow.continuations.SuspendApp
import arrow.continuations.ktor.server
import arrow.core.raise.result
import arrow.fx.coroutines.resourceScope
import io.github.nomisRev.kafka.receiver.ReceiverRecord
import io.ktor.http.ContentType
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticate
import io.ktor.server.netty.Netty
import io.ktor.server.routing.routing
import io.ktor.utils.io.CancellationException
import io.micrometer.prometheusmetrics.PrometheusConfig
import io.micrometer.prometheusmetrics.PrometheusMeterRegistry
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import no.nav.emottak.ebms.AZURE_AD_AUTH
import no.nav.emottak.ebms.CpaRepoClient
import no.nav.emottak.ebms.EBMS_PAYLOAD_SCOPE
import no.nav.emottak.ebms.EBMS_SEND_IN_SCOPE
import no.nav.emottak.ebms.EVENT_MANAGER_SCOPE
import no.nav.emottak.ebms.EventManagerClient
import no.nav.emottak.ebms.PayloadProcessingClient
import no.nav.emottak.ebms.SMTP_TRANSPORT_SCOPE
import no.nav.emottak.ebms.SendInClient
import no.nav.emottak.ebms.SmtpTransportClient
import no.nav.emottak.ebms.async.configuration.Config
import no.nav.emottak.ebms.async.configuration.config
import no.nav.emottak.ebms.async.kafka.consumer.FailedMessageKafkaHandler
import no.nav.emottak.ebms.async.kafka.consumer.startEbmsOutPayloadReceiver
import no.nav.emottak.ebms.async.kafka.consumer.startPayloadReceiver
import no.nav.emottak.ebms.async.kafka.consumer.startSignalReceiver
import no.nav.emottak.ebms.async.kafka.producer.EbmsMessageProducer
import no.nav.emottak.ebms.async.persistence.Database
import no.nav.emottak.ebms.async.persistence.ebmsDbConfig
import no.nav.emottak.ebms.async.persistence.ebmsMigrationConfig
import no.nav.emottak.ebms.async.persistence.repository.MessagePendingAckRepository
import no.nav.emottak.ebms.async.persistence.repository.PayloadRepository
import no.nav.emottak.ebms.async.processing.MessageFilterService
import no.nav.emottak.ebms.async.processing.PayloadMessageForwardingService
import no.nav.emottak.ebms.async.processing.PayloadMessageService
import no.nav.emottak.ebms.async.processing.RetryService
import no.nav.emottak.ebms.async.processing.SignalMessageService
import no.nav.emottak.ebms.async.processing.sendSignalResponseToTopic
import no.nav.emottak.ebms.async.util.EventRegistrationService
import no.nav.emottak.ebms.async.util.EventRegistrationServiceImpl
import no.nav.emottak.ebms.defaultHttpClient
import no.nav.emottak.ebms.eventmanager.EventManagerService
import no.nav.emottak.ebms.processing.ProcessingService
import no.nav.emottak.ebms.registerHealthEndpoints
import no.nav.emottak.ebms.registerNavCheckStatus
import no.nav.emottak.ebms.registerPrometheusEndpoint
import no.nav.emottak.ebms.registerRootEndpoint
import no.nav.emottak.ebms.scopedAuthHttpClient
import no.nav.emottak.ebms.sendin.SendInService
import no.nav.emottak.ebms.validation.CPAValidationService
import no.nav.emottak.message.model.Payload
import no.nav.emottak.message.model.PayloadMessage
import no.nav.emottak.utils.common.model.SendInResponse
import no.nav.emottak.utils.environment.getEnvVar
import no.nav.emottak.utils.environment.isProdEnv
import no.nav.emottak.utils.kafka.client.EventPublisherClient
import no.nav.emottak.utils.kafka.service.EventLoggingService
import org.slf4j.LoggerFactory
import kotlin.concurrent.timer

val log = LoggerFactory.getLogger("no.nav.emottak.ebms.async.App")

fun main() = SuspendApp {
    val database = Database(ebmsDbConfig.value)
    database.migrate(ebmsMigrationConfig.value)
    val payloadRepository = PayloadRepository(database)

    val config = config()

    val useAsyncOutbound = getEnvVar("USE_ASYNC_OUT", "false").toBoolean()
    if (useAsyncOutbound) {
        log.info("Starting OUT receiver, asynchronous responses/outgoing messages will be processed.")
    } else {
        log.info("OUT receiver is OFF, asynchronous responses/outgoing messages will NOT be processed.")
    }
    val useAsyncInbound = getEnvVar("USE_ASYNC_IN", "false").toBoolean()
    if (useAsyncInbound) {
        log.info("Async IN is ON, inbound messages will be forwarded asynchronously.")
    } else {
        log.info("Async IN is OFF, inbound messages will be forwarded synchronously.")
    }

    val messagePendingAckRepository = MessagePendingAckRepository(database, config.messageResendPolicy.resendInterval, config.messageResendPolicy.maxResends)

    val failedMessageQueue = FailedMessageKafkaHandler()

    val processingService = ProcessingService(
        httpClient = PayloadProcessingClient(scopedAuthHttpClient(EBMS_PAYLOAD_SCOPE))
    )
    val cpaValidationService = CPAValidationService(
        httpClient = CpaRepoClient(defaultHttpClient())
    )
    val sendInService = SendInService(
        httpClient = SendInClient(scopedAuthHttpClient(EBMS_SEND_IN_SCOPE))
    )

    val ebmsSignalProducer = EbmsMessageProducer(config.kafkaSignalProducer.topic, config.kafka)
    val ebmsPayloadProducer = EbmsMessageProducer(config.kafkaPayloadProducer.topic, config.kafka)
    val ebmsInPayloadProducer = EbmsMessageProducer(config.kafkaEbmsInPayloadProducer.topic, config.kafka)

    val smtpTransportClient = SmtpTransportClient(scopedAuthHttpClient(SMTP_TRANSPORT_SCOPE))

    val eventManagerService = EventManagerService(
        EventManagerClient(scopedAuthHttpClient(EVENT_MANAGER_SCOPE))
    )
    val eventRegistrationService = EventRegistrationServiceImpl(
        EventLoggingService(config().eventLogging, EventPublisherClient(config().kafka))
    )

    val payloadMessageForwardingService = PayloadMessageForwardingService(
        sendInService = sendInService,
        cpaValidationService = cpaValidationService,
        processingService = processingService,
        payloadRepository = payloadRepository,
        ebmsPayloadProducer = ebmsPayloadProducer,
        ebmsInPayloadProducer = ebmsInPayloadProducer,
        eventRegistrationService = eventRegistrationService,
        messagePendingAckRepository = messagePendingAckRepository
    )

    val retryService = RetryService(
        cpaValidationService = cpaValidationService,
        eventRegistrationService = eventRegistrationService,
        failedMessageKafkaHandler = failedMessageQueue,
        signalSender = { ebmsDocument, signalResponderEmails ->
            sendSignalResponseToTopic(ebmsSignalProducer, eventRegistrationService, ebmsDocument, signalResponderEmails)
        }
    )

    val payloadMessageService = PayloadMessageService(
        cpaValidationService = cpaValidationService,
        processingService = processingService,
        ebmsSignalProducer = ebmsSignalProducer,
        payloadMessageForwardingService = payloadMessageForwardingService,
        eventRegistrationService = eventRegistrationService,
        eventManagerService = eventManagerService,
        retryService = retryService,
        useAsyncInbound
    )

    val signalMessageService = SignalMessageService(
        cpaValidationService = cpaValidationService,
        eventRegistrationService = eventRegistrationService,
        messagePendingAckRepository = messagePendingAckRepository
    )

    val messageFilterService = MessageFilterService(
        payloadMessageService = payloadMessageService,
        signalMessageService = signalMessageService,
        smtpTransportClient = smtpTransportClient,
        eventRegistrationService = eventRegistrationService
    )

    val pauseRetryErrorsTimerFlag = PauseRetryErrorsTimerFlag()

    result {
        resourceScope {
            launchSignalReceiver(
                config = config,
                messageFilterService = messageFilterService
            )
            launchPayloadReceiver(
                config = config,
                messageFilterService = messageFilterService
            )
            launchEbmsOutPayloadReceiver(
                config = config,
                payloadMessageService = payloadMessageService
            )
            launchErrorRetryTaskIncoming(
                config = config,
                retryService = retryService,
                messageFilterService = messageFilterService,
                pauseRetryErrorsTimerFlag = pauseRetryErrorsTimerFlag
            )
            launchErrorRetryTaskOutgoing(
                config = config,
                retryService = retryService,
                payloadMessageService = payloadMessageService,
                pauseRetryErrorsTimerFlag = pauseRetryErrorsTimerFlag
            )
            launchMesssageResendTask(
                config = config,
                messagePendingAckRepository = messagePendingAckRepository,
                payloadMessageForwardingService = payloadMessageForwardingService
            )

            server(
                Netty,
                port = 8080,
                module = {
                    ebmsProviderModule(
                        payloadRepository = payloadRepository,
                        messageFilterService = messageFilterService,
                        eventRegistrationService = eventRegistrationService,
                        retryService = retryService,
                        payloadMessageService = payloadMessageService,
                        pauseRetryErrorsTimerFlag = pauseRetryErrorsTimerFlag,
                        failedMessageQueue = failedMessageQueue,
                        messagePendingAckRepository = messagePendingAckRepository
                    )
                }
            ).also { it.engineConfig.maxChunkSize = 100000 }

            awaitCancellation()
        }
    }
        .onFailure { error ->
            when (error) {
                is CancellationException -> {} // expected behaviour - normal shutdown
                else -> log.error("Unexpected shutdown initiated", error)
            }
        }
}
class PauseRetryErrorsTimerFlag {
    var paused = false
}

fun CoroutineScope.launchPayloadReceiver(
    config: Config,
    messageFilterService: MessageFilterService
) {
    if (config.kafkaPayloadReceiver.active) {
        launch(Dispatchers.IO) {
            startPayloadReceiver(
                config.kafkaPayloadReceiver.topic,
                config.kafka,
                messageFilterService
            )
        }
    }
}

fun CoroutineScope.launchEbmsOutPayloadReceiver(
    config: Config,
    payloadMessageService: PayloadMessageService
) {
    if (config.kafkaEbmsOutPayloadReceiver.active) {
        launch(Dispatchers.IO) {
            startEbmsOutPayloadReceiver(
                config.kafkaEbmsOutPayloadReceiver.topic,
                config.kafka,
                payloadMessageService
            )
        }
    }
}

fun CoroutineScope.launchSignalReceiver(
    config: Config,
    messageFilterService: MessageFilterService
) {
    if (config.kafkaSignalReceiver.active) {
        launch(Dispatchers.IO) {
            startSignalReceiver(
                config.kafkaSignalReceiver.topic,
                config.kafka,
                messageFilterService = messageFilterService
            )
        }
    }
}

/**
 * Builds the OUT-direction retry processor lambda.
 * Decodes the stored SendInResponse from the record and delegates to
 * [PayloadMessageService.processOutboundResponse], mirroring the live receive path in EbmsOutPayloadReceiver.
 */
fun makeOutRetryProcessor(
    payloadMessageService: PayloadMessageService
): suspend (ReceiverRecord<String, ByteArray>) -> Unit = { record ->
    val sendInResponse = Json.decodeFromString<SendInResponse>(record.value().decodeToString())
    val cpaId = record.headers().lastHeader("cpaId")?.let { String(it.value()) } ?: ""
    val refToMessageId = record.headers().lastHeader("refToMessageId")?.let { String(it.value()) }
    val payloadMessage = PayloadMessage(
        requestId = sendInResponse.requestId,
        messageId = sendInResponse.messageId,
        conversationId = sendInResponse.conversationId,
        cpaId = cpaId,
        addressing = sendInResponse.addressing,
        payload = Payload(sendInResponse.payload, ContentType.Application.Xml.toString()),
        refToMessageId = refToMessageId,
        duplicateElimination = false,
        ackRequested = true
    )
    payloadMessageService.processOutboundResponse(record, payloadMessage)
}

fun CoroutineScope.launchErrorRetryTaskIncoming(
    config: Config,
    retryService: RetryService,
    messageFilterService: MessageFilterService,
    pauseRetryErrorsTimerFlag: PauseRetryErrorsTimerFlag
) {
    if (!config.kafkaErrorQueue.active) return

    timer(
        name = "Retry Errors Timer Incoming",
        initialDelay = 5000L,
        period = config.errorRetryPolicyIncoming.processInterval.inWholeMilliseconds,
        daemon = true
    ) {
        launch(Dispatchers.IO) {
            log.info("=== RetryErrorsTaskIncoming starting...")
            try {
                if (pauseRetryErrorsTimerFlag.paused) {
                    log.info("Retry task is paused.")
                    return@launch
                }
                retryService.consumeRetryQueueIncoming(
                    limit = config.errorRetryPolicyIncoming.maxMessagesToProcess,
                    processor = messageFilterService::filterMessage
                )
            } catch (e: Exception) {
                log.error("RetryErrorsTaskIncoming failed", e)
            }
        }
    }
}

fun CoroutineScope.launchErrorRetryTaskOutgoing(
    config: Config,
    retryService: RetryService,
    payloadMessageService: PayloadMessageService,
    pauseRetryErrorsTimerFlag: PauseRetryErrorsTimerFlag
) {
    if (!config.kafkaErrorQueueOut.active) return

    timer(
        name = "Retry Errors Timer Outgoing",
        initialDelay = 5000L,
        period = config.errorRetryPolicyOutgoing.processInterval.inWholeMilliseconds,
        daemon = true
    ) {
        launch(Dispatchers.IO) {
            log.info("=== RetryErrorsTaskOutgoing starting...")
            try {
                if (pauseRetryErrorsTimerFlag.paused) {
                    log.info("Retry task is paused.")
                    return@launch
                }
                retryService.consumeRetryQueueOutgoing(
                    limit = config.errorRetryPolicyOutgoing.maxMessagesToProcess,
                    processor = makeOutRetryProcessor(payloadMessageService)
                )
            } catch (e: Exception) {
                log.error("RetryErrorsTaskOutgoing failed", e)
            }
        }
    }
}

fun CoroutineScope.launchMesssageResendTask(
    config: Config,
    messagePendingAckRepository: MessagePendingAckRepository,
    payloadMessageForwardingService: PayloadMessageForwardingService
) {
    timer(
        name = "Resend Messages Timer",
        initialDelay = 5000L,
        period = config.messageResendPolicy.processInterval.inWholeMilliseconds,
        daemon = true
    ) {
        launch(Dispatchers.IO) {
            log.info("=== MessageResendTask starting...")
            try {
                val messagesToResend = messagePendingAckRepository.findMessagesToResend()
                log.info("Found ${messagesToResend.size} messages to be resent because of missing Ack")
                for (message in messagesToResend) {
                    payloadMessageForwardingService.resendMessage(message)
                    messagePendingAckRepository.markResent(message)
                }
            } catch (e: Exception) {
                log.error("MessageResendTask failed", e)
            }
        }
    }
}

fun Application.ebmsProviderModule(
    payloadRepository: PayloadRepository,
    messageFilterService: MessageFilterService,
    eventRegistrationService: EventRegistrationService,
    retryService: RetryService,
    payloadMessageService: PayloadMessageService,
    pauseRetryErrorsTimerFlag: PauseRetryErrorsTimerFlag,
    failedMessageQueue: FailedMessageKafkaHandler,
    messagePendingAckRepository: MessagePendingAckRepository
) {
    val appMicrometerRegistry = PrometheusMeterRegistry(PrometheusConfig.DEFAULT)

    installMicrometerRegistry(appMicrometerRegistry)
    installContentNegotiation()
    installAuthentication()

    routing {
        registerRootEndpoint()
        registerHealthEndpoints()
        registerPrometheusEndpoint(appMicrometerRegistry)
        registerNavCheckStatus()
        if (!isProdEnv()) {
            forceRetryMessageIn(retryService)
            forceRetryMessageOut(retryService)
        }
        retryErrorsIncoming(retryService, messageFilterService)
        retryErrorsOutgoing(retryService, payloadMessageService)
        rerun(retryService, messageFilterService)
        pauseRetries(pauseRetryErrorsTimerFlag)
        resumeRetries(pauseRetryErrorsTimerFlag)
        unacknowledge(messagePendingAckRepository)
        authenticate(AZURE_AD_AUTH) {
            getPayloads(payloadRepository, eventRegistrationService)
        }
    }
}
