/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.9.0"
    application
    id("io.ktor.plugin") version "2.3.4"
}

repositories {
    mavenCentral()
}

tasks.register<Wrapper>("wrapper") {
    gradleVersion="8.1.1"
}

dependencies {
    implementation("io.ktor:ktor-server-core:2.3.4")
    implementation("io.ktor:ktor-server-netty:2.3.4")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")
    // https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
    //implementation("javax.xml.bind:jaxb-api:2.2.4")

}

application {
    mainClass.set("ebxml.processor.app.AppKt")
}
