package no.nav.emottak.utils.events.model

enum class EventType(val value: Int, val description: String) {
    MESSAGE_VALIDATED(127, "Melding validert"),
    MESSAGE_CRYPTED(101, "Melding kryptert"),
    APPREC_PRODUCED(102, "Applikasjonskvittering produsert"),
    APPREC_SENT(103, "Applikasjonskvittering sendt"),
    MESSAGE_RESENT(106, "Melding resendt"),
    FNR_LOOKUP_COMPLETED(114, "Fødselsnummeroppslag utført"),
    TRANSPORT_RECEIPT_RECEIVED(119, "Transport kvittering mottatt"),
    MESSAGE_RETREIVED_FROM_EMAIL(120, "Melding hentet fra e-post"),
    MESSAGE_DECRYPTED(124, "Melding dekryptert"),
    SIGNATURE_VERIFIED(133, "Signatur verifisert"),
    MESSAGE_STORED_IN_JUIDISK_LOGG(136, "Melding lagret i juridisk logg"),
    MESSAGE_SENT_TO_INTERNAL_ADAPTER(148, "Melding sendt til internt adapter"),
    MESSAGE_SIGNED(150, "Melding signert"),
    MESSAGE_COMPRESSED(153, "Melding komprimert"),
    MESSAGE_SENT(154, "Melding sendt"),
    MESSAGE_RECEIVED_FROM_INTERNAL(155, "Melding mottatt fra intern avsender"),
    MESSAGE_DECOMPRESSED(157, "Melding dekomprimert"),
    MESSAGE_ADDED_TO_FELLESFORMAT(158, "Melding lagt i fellesformat"),
    FELLESFORMAT_UPDATED_WITH_FNR(159, "Fellesformat oppdatert med fødselsnummer"),
    FELLESFORMAT_UPDATED_WITH_ORGNR(160, "Fellesformat oppdatert med orgnummer"),
    FELLESFORMAT_UPDATED_WITH_TIMESTAMP(161, "Fellesformat oppdatert med tidsstempel"),
    RULE_PROCESSING_PERFORMED(162, "Regelbehandling utført"),
    SERVICE_ACTION_UPDATED(163, "Service/Action oppdatert"),
    XML_INFO_RETREIVED_FROM_MESSAGE(164, "XML-informasjon hentet fra melding"),
    MESSAGE_UNPACKED_FROM_FELLESFORMAT(172, "Melding pakket ut av fellesformat"),
    MESSAGE_SENT_TO_QUEUE(187, "Melding lagt på kø"),
    MESSAGE_PROCESS_COMPLETED(188, "Melding ferdig behandlet"),
    MESSAGE_RECEIVED_FROM_WEBSERVICE(189, "Melding mottatt fra WebService"),
    MESSAGE_RECEIVED_FROM_HTTP(190, "Melding mottatt fra http"),
    SERVICE_CALL_EXECUTED(191, "Service kall utført"),
    MESSAGE_GENERATED(192, "Melding generert"),
    MESSAGE_FAILED_IN_SECURITYSYSTEMS(211, "Melding feilet i sikkerhetstjenestene!"),
    MESSAGE_HAS_SYNTAX_ERRORS(212, "Melding har syntaksfeil"),
    MESSAGE_CANNOT_BE_DECRYPTED(213, "Melding kan ikke dekrypteres"),
    MESSAGE_CANNOT_BE_CRYPTED(214, "Melding kan ikke krypteres"),
    SIGNATURE_NOT_OK(216, "Signatursjekk ikke OK"),
    UNKNOWN_ERROR_OCCURED(218, "Ukjent feil oppsto!"),
    VALIDATION_RULE_FOR_MESSAGE_NOT_FOUND(220, "Valideringsregel for melding ikke funnet"),
    MESSAGE_CANNOT_BE_SIGNED_BY_NAV(222, "Melding kan ikke signeres av NAV"),
    MESSAGE_FAILED_IN_CPA(223, "Melding feilet i CPA-tjenestene!"),
    MESSAGE_FAILED_IN_FNR_SYSTEM(226, "Melding feilet i fødselsnummertjenesten!"),
    ERROR_OCCURED_DURING_XML_PARSING(227, "Feil oppsto under XML-parsing!"),
    UNKNOWN_PARTNER_PROFILE(236, "Ukjent partner profil"),
    MESSAGE_NOT_SENT(241, "Melding ble IKKE sendt"),
    MESSAGE_NOT_ADDED_TO_FELLESFORMAT(244, "Melding ikke lagt i fellesformat"),
    CHARSET_NOT_FOUND(250, "Tegnsett ikke funnet"),
    MESSAGE_REJECTED_DUPLICATE_ACK_SENT(253, "Melding avvist som duplikat. (ebXML Ack sendt)"),
    MESSAGE_REJECTED(254, "Melding forkastet"),
    MESSAGE_CONFIG_NOT_FOUND(256, "Meldingskonfigurasjon ikke funnet"),
    ERROR_SENDING_TO_QUEUE(257, "Feil under sending til kø"),
    JMS_SYSTEM_EXCEPTION(301, "JMS_System exception."),
    MESSAGE_FAILED_DURING_VALIDATION(231, "Melding feilet i validering!"),
    STORE_TO_JURIDISK_LOGG_RESERVE_FAILED(261, "Lagring i reserveområdet for juridisk logg feilet"),
    TIMEOUT(262, "Timeout"),
    MESSAGE_FAILED_AT_BACKEND(263, "Melding feilet hos mottaker"),
    MESSAGE_DELIVERY_FAILED(264, "Melding kunne ikke leveres"),
    MESSAGE_NOT_DELIVERED_UNKNOWN_REASON(265, "Melding kunne ikke leveres av ukjent grunn"),
    SIGNATURE_CHECK_FAILED_CERTIFICATE_ERROR(266, "Signatursjekk ikke OK, feil på sertifikat"),
    UNKNOWN_BREVKODE(267, "Ukjent brevkode"),
    SERVICE_CALL_FAILED(268, "Service kall feilet"),
    MESSAGE_REQUIREMENTS_NOT_MEET_FOR_PARTNER_PROFILE(269, "Melding oppfyller ikke partners profil"),
    NO_CONTACT_WITH_PARTNER_SERVER(270, "Fikk ikke kontakt med partners server"),
    MESSAGE_NOT_DELIVERED_SUBSCRIPTION_NULL(271, "Meldingen kunne ikke leveres pga subscription er null"),
    XML_SYSTEM_EXCEPTION(303, "XML_System exception."),
    LISTENER_STOPPED_FOR_EBXML_TRAFFIC(310, "Stoppet lytter på ebXML-trafikk"),
    RULE_SYSTEM_EXCEPTION_LISTENER_STOPPED(304, "Regel System exception. Lytter stoppet!"),
    FNR_SYSTEM_EXCEPTION_LISTENER_STOPPED(305, "FNR System exception. Lytter stoppet!"),
    PKI_SYSTEM_EXCEPTION_LISTENER_STOPPED(306, "PKI System exception. Lytter stoppet!"),
    DB_SYSTEM_EXCEPTION_LISTENER_STOPPED(308, "DBService System exception. Lytter stoppet!"),
    JURIDISK_LOGG_SYSTEM_EXCEPTION_LISTENER_STOPPED(309, "JuridiskLogg System exception. Lytter stoppet!"),
    MQ_MSG_DELETED(813, "MQ-melding slettet"),
    MQ_MSG_COPIED(814, "MQ-melding kopiert"),
    MQ_MSG_MOVED(815, "MQ-melding flyttet"),
    CERTIFICATE_ADDED(816, "Sertifikat lagt til"),
    KEYPAIR_ADDED(817, "Nøkkelpar lagt til"),
    CERTIFICATE_DELETED(818, "Sertifikat slettet"),
    SSN_CACHE_FLUSHED(800, "SSN cache flushed"),
    SSN_CACHE_DELETED(801, "SSN cache slettet"),
    PROCESSING_RULE_NOT_FOUND(201, "Behandlingsregel ikke funnet!"),
    MESSAGE_CANNOT_BE_RESENT(202, "Melding kan ikke resendes"),
    XML_MESSAGE_CANNOT_BE_DECOMPRESSED(203, "XML-melding kan ikke dekomprimeres"),
    TRANSPORT_RECEIPT_NOT_RECEIVED(207, "Transport kvittering ikke mottatt"),
    INVALID_APPREC(228, "Ugyldig applikasjonskvittering!"),
    UNKNOWN_MESSAGETYPE_RECEIVED(229, "Ukjent meldingstype mottatt!"),
    INVALID_XML_MESSAGE(259, "Ugyldig XML-melding"),
    IN_ENVELOPE_NOT_FOUND(260, "Innkonvolutt ikke funnet"),
    LOG_SYSTEM_EXCEPTION(302, "Logg System exception."),
    MDP_STOP(821, "MDP stopp"),
    MDP_START(822, "MDP start"),
    MDP_SHUTDOWN(823, "MDP shutdown"),
    MDP_INITIALIZED(824, "MDP initialisert"),
    SUBSCRIPTION_TERMINATED(840, "Abonnement avsluttet"),
    ARTIFACT_PRODUCED(841, "Produsert artifakt"),
    JOB_SUSPENDED(835, "Jobb suspendert"),
    JOB_SUSPENSATION_REVOKED(836, "Jobb suspensjon opphevet"),
    JOB_EXECUTED(837, "Jobb eksekvert");

    companion object {
        fun fromInt(eventCode: Int): EventType {
            return EventType.entries.find {
                it.value == eventCode
            } ?: throw IllegalArgumentException("Unrecognized EventType code value: $eventCode")
        }
        fun fromString(description: String): EventType {
            return EventType.entries.find {
                it.description.equals(description)
            } ?: throw IllegalArgumentException("Unrecognized EventType description: '$description'")
        }
    }
}
