/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    java
    id("org.springframework.boot") version "3.1.3"
    id("io.freefair.lombok") version "8.3"
}

apply(plugin = "io.spring.dependency-management")

repositories {
    mavenCentral()
}

tasks.register<Wrapper>("wrapper") {
    gradleVersion="8.1.1"
}

dependencies {
    implementation(project(":list"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.kafka:spring-kafka")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.projectlombok:lombok")
    implementation("jakarta.mail:jakarta.mail-api")
    implementation("org.eclipse.angus:jakarta.mail:1.0.0")
    testImplementation("org.springframework.kafka:spring-kafka-test")
    testImplementation("org.springframework.boot:spring-boot-starter-test")

}
