/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ebxml.processor.app

import io.ktor.http.*
import io.ktor.http.content.*
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun main() {
    embeddedServer(Netty, port = 8080) {
        routing {
            get("/") {
                call.respondText("Hello, world!")
            }
            post("/ebms") {
                call.receiveMultipart().forEachPart {
                    print( it is PartData.BinaryItem)
                    print(it.contentDisposition?.disposition)
                    print( it is PartData.FileItem)
                }
                call.respondText("Hello")
            }
        }
    }.start(wait = true)
}
