/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
}

tasks {
    register<Wrapper>("wrapper") {
        gradleVersion="8.1.1"
    }
    test {
        useJUnitPlatform()
    }
}

dependencies {
    implementation(libs.ebxml.protokoll)
    implementation(libs.emottak.payload.xsd)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.bundles.logging)
    runtimeOnly("org.postgresql:postgresql:42.6.0")
}

