/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.emottak.cpa

import io.ktor.http.content.*
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun main() {

    embeddedServer(Netty, port = 8080) {
        routing {
            get("/cpa") {
                call.respondText("Hello, world!")
            }
        }
    }.start(wait = true)
}

fun PartData.FormItem.payload() : ByteArray {
    return java.util.Base64.getMimeDecoder().decode(this.value)
}
