name: "Build and deploy ebxml-processor"
on:
  push:
    branches:
    - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "actions/setup-java@v3"
      with:
        "java-version": "17"
        "distribution": "temurin"
    - name: Cache gradle wrapper
      uses: actions/cache@v3
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle') }}
        restore-keys: |
            ${{ runner.os }}-gradle-cache-
    
    - name: "compile and run tests"
      run: ./gradlew test build
      env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build and push the Docker image"
      run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"
#  "deployAppToDev":
#    name: "Deploy app to dev"
#    needs: "build"
#    runs-on: "ubuntu-20.04"
#    steps:
#    - uses: "actions/checkout@v3"
#    - name: "Deploy to DEV"
#      uses: "nais/deploy/actions/deploy@v1"
#      env:
#        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#        "CLUSTER": "dev-gcp"
#        "RESOURCE": ".nais/nais.yaml"
#        "VARS": ".nais/dev.yaml"
#  "deployAppToProd":
#    name: "Deploy app to prod"
#    needs: "deployAppToDev"
#    runs-on: "ubuntu-20.04"
#    steps:
#    - uses: "actions/checkout@v3"
#    - name: "Deploy to PROD"
#      uses: "nais/deploy/actions/deploy@v1"
#      env:
#        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#        "CLUSTER": "prod-gcp"
#        "RESOURCE": ".nais/nais.yaml"
#        "VARS": ".nais/prod.yaml"
