name: "Build and deploy (via build.yaml)"
on:
  workflow_dispatch:
  push:
    branches:
      - main2
      - dev2/**
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-20.04"
    permissions:
      packages: write
      repository-projects: write
      contents: write
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Cache gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: "Build and tests"
        run: ./gradlew test build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push ebms-provider
        uses: nais/docker-build-push@v0
        id: docker-push-ebms-provider
        with:
          team: team-emottak # required
          tag: ${{ github.sha }}
          dockerfile: Dockerfile # optional, default Dockerfile
          docker_context: ebms-provider # optional, default .
          image_suffix: ebms-provider
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
      - name: Docker build and push ebms-payload
        uses: nais/docker-build-push@v0
        id: docker-push-ebms-payload
        with:
          team: team-emottak # required
          tag: ${{ github.sha }}
          dockerfile: Dockerfile # optional, default Dockerfile
          docker_context: ebms-payload # optional, default .
          image_suffix: ebms-payload
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
      - name: Docker build and push cpa-repo
        uses: nais/docker-build-push@v0
        id: docker-push-cpa-repo
        with:
          team: team-emottak # required
          tag: ${{ github.sha }}
          dockerfile: Dockerfile # optional, default Dockerfile
          docker_context: cpa-repo # optional, default .
          image_suffix: cpa-repo
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
    outputs:
      providerimage: ${{ steps.docker-push-ebms-provider.outputs.image }}
      payloadimage: ${{ steps.docker-push-ebms-payload.outputs.image }}
      cpaimage: ${{ steps.docker-push-cpa-repo.outputs.image }}
  deploy-processor:
    name: "Deploy ebms provider to dev"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "dev-fss"
          RESOURCE: ".nais/ebms-provider-dev.yaml"
          IMAGE: ${{ needs.build.outputs.providerimage }}
          TELEMETRY: ${{ steps.docker-push-ebms-provider.outputs.telemetry }}
  deploy-cpa-repo:
    name: "Deploy cpa-repo to dev"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "dev-fss"
          RESOURCE: ".nais/cpa-repo-dev.yaml"
          IMAGE: ${{ needs.build.outputs.cpaimage }}
          TELEMETRY: ${{ steps.docker-push-cpa-repo.outputs.telemetry }}
  deploy-ebms-payload:
    name: "Deploy ebms-payload to dev"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "dev-fss"
          RESOURCE: ".nais/ebms-payload-dev.yaml"
          IMAGE: ${{ needs.build.outputs.payloadimage }}
          TELEMETRY: ${{ steps.docker-push-ebms-payload.outputs.telemetry }}
