name: "Publish emottak-utils library"
on:
  workflow_dispatch:
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-24.04"
    permissions: 
        packages: write
        repository-projects: write
        contents: write
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-java@v3"
      with:
        "java-version": "21"
        "distribution": "temurin"
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: "Build and tests"
      run: ./gradlew test build
      env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish emottak-utils
      run: ./gradlew emottak-utils:publish
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: x-access-token
        GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
