name: "Build and deploy ebxml-processor"
on:
  push:
    branches:
    - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "actions/cache@v3"
      with:
        "path": "~/.m2/repository"
        "key": "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
        "restore-keys": "${{ runner.os }}-maven-"
    - uses: "actions/setup-java@v3"
      with:
        "java-version": "17"
    - name: "compile and run tests"
      run: "mvn install"
    - name: "Login to GitHub Docker Registry"
      uses: "docker/login-action@v2"
      with:
        "registry": "ghcr.io"
        "username": "${{ github.actor }}"
        "password": "${{ secrets.GITHUB_TOKEN }}"
    - name: "Build and push the Docker image"
      run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"
  "deployAppToDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Deploy to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-gcp"
        "RESOURCE": ".nais/nais.yaml"
        "VARS": ".nais/dev.yaml"
  "deployAppToProd":
    name: "Deploy app to prod"
    needs: "deployAppToDev"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Deploy to PROD"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "prod-gcp"
        "RESOURCE": ".nais/nais.yaml"
        "VARS": ".nais/prod.yaml"
  "deployAlertsToDev":
    name: "Deploy alerts to dev"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Deploy alerts to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-gcp"
        "RESOURCE": ".nais/alerts-dev.yaml"
        "VARS": ".nais/dev.yaml"
  "deployAlertsToProd":
    name: "Deploy alerts to prod"
    needs: "build"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Deploy alerts to PROD"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "prod-gcp"
        "RESOURCE": ".nais/alerts-prod.yaml"
        "VARS": ".nais/prod.yaml"