/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
}

tasks.register<Wrapper>("wrapper") {
    gradleVersion="8.1.1"
}

dependencies {
    implementation("no.nav.emottak:ebxml-protokoll:0.0.4")
    implementation("com.zaxxer:HikariCP:5.0.1")
    implementation("org.flywaydb:flyway-core:9.16.3")
    implementation("ch.qos.logback:logback-classic:1.4.11")
    implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.4")
    api("org.bouncycastle:bcprov-jdk18on:1.76")
    api("org.bouncycastle:bcpkix-jdk18on:1.76")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")

    runtimeOnly("org.postgresql:postgresql:42.6.0")
}

